In [12]:
import numpy as np 
import gymnasium as gym
import numpy as np
import sys


In [13]:
if "../" not in sys.path:
  sys.path.append("../") 

from lib.envs import discrete

In [14]:

a = np.arange(6).reshape(2,3)
it = np.nditer(a)

dir(it)

['__class__',
 '__copy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__enter__',
 '__eq__',
 '__exit__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__next__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'close',
 'copy',
 'debug_print',
 'dtypes',
 'enable_external_loop',
 'finished',
 'has_delayed_bufalloc',
 'has_index',
 'has_multi_index',
 'index',
 'iterationneedsapi',
 'iterindex',
 'iternext',
 'iterrange',
 'itersize',
 'itviews',
 'multi_index',
 'ndim',
 'nop',
 'operands',
 'remove_axis',
 'remove_multi_index',
 'reset',
 'shape',
 'value']

In [26]:
np_1 = np.zeros([3,4])
np_1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
terminal = np.zeros([3,4], dtype =bool)
terminal[0][3]= True

In [28]:
terminal

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [30]:
np_1[terminal] = 100

In [31]:
np_1

array([[  0.,   0.,   0., 100.],
       [  0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.]])

In [32]:
is_done = lambda d: d == terminal[y][x]

In [34]:
np.array([np.array([3,4]), 5])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [35]:
    def _calculate_transition_prob(current, delta, winds):
        new_position = np.array(current) + np.array(delta) + np.array([-1, 0]) * winds[tuple(current)]
        new_position =  _limit_coordinates(new_position).astype(int)
        new_state = np.ravel_multi_index(tuple(new_position),  shape)
        is_done = tuple(new_position) == (3, 7)
        return [(1.0, new_state, -1.0, is_done)]

In [39]:

s = 5
np.unravel_index(s, [3 , 6])

(0, 5)

In [63]:
type(np.array([4,5])[1])

isinstance(np.array([4,5])[1], np.int64)

True

In [58]:
dict_a = {'5':'9', '4':'6'}
isinstance(dict_a, int)


False

In [49]:
for key in dict_a:
    print(key)

5
4


In [67]:
x = dict_a

if x:
    print('x is true')
else:
    print('x is false')

x is true


In [70]:
x is None

False

In [75]:
bool(0)

False

In [83]:
board = np.arange(10).reshape(2,5)
coord = np.array([1,4])
board

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [82]:
board[coord[0], coord[1]]

9

In [87]:
0//2

0

In [88]:
np.array(np.array([3,4]))

array([3, 4])

In [91]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])