In [1]:
import numpy as np
import pprint
import sys
if "../" not in sys.path:
  sys.path.append("../") 
from lib.envs.gridworld import GridworldEnv

In [2]:
pp = pprint.PrettyPrinter(indent=2)
env = GridworldEnv()

In [45]:
def value_iteration(env, theta=0.0001, discount_factor=1.0):
    """
    Value Iteration Algorithm.
    
    Args:
        env: OpenAI env. env.P represents the transition probabilities of the environment.
            env.P[s][a] is a list of transition tuples (prob, next_state, reward, done).
            env.nS is a number of states in the environment. 
            env.nA is a number of actions in the environment.
        theta: We stop evaluation once our value function change is less than theta for all states.
        discount_factor: Gamma discount factor.
        
    Returns:
        A tuple (policy, V) of the optimal policy and the optimal value function.        
    """
    
    # initialize both estimnated value of the optimal policy
    # and the estimated optimal policy itself:

    V = np.zeros(env.nS)
    policy = np.zeros([env.nS, env.nA])
    
    number_loop = 0
    # Implement:
    # update loop:
    while True:
        number_loop += 1 
        # first, get the best policy under the current V:
        V_before_update = V.copy()
       # print('V_before_update: ', V_before_update)
        for s in range(env.nS):
                    # max over all actions in outer loop:
            V[s] = max([
                                    np.sum([ 
                                        # inner loop, 
                                        # loop through all possible outcomes , then sum over to get expected
                                        # for each fixed action from the outer loop
                                         prob*(reward + discount_factor*V[next_state])   for (prob, next_state, reward, __ ) in env.P[s][a] ])
                                    for a in range(env.nA)]
                                    )
            
        # after looping through all states, check whether the max difference
            # between the updated V and original V over all states is less than theta:
        # print('after one loop, V_before_update:', V_before_update)
        # print('V is ', V)
        delta = np.max(np.abs(V - V_before_update))
        # print('latest V: ' , V)


        # V = np.array(
        #     [np.argmax([ 
        #         np.sum([  ]) for s in range(env.nS)
        #         ])]
        #     )



        # 
    
        print('delta: ', delta)
        if delta < theta:
            print('ending training.....')
            print('total num of updates through all updates:', number_loop)
            break 





    for s in range(env.nS):
        policy[s] = np.argmax([
                                    np.sum([ 
                                        # inner loop, 
                                        # loop through all possible outcomes , then sum over to get expected
                                        # for each fixed action from the outer loop
                                         prob*(reward + discount_factor*V[next_state])   for (prob, next_state, reward, __ ) in env.P[s][a] ])
                                    for a in range(env.nA)])


    return policy, V

In [46]:
policy, v = value_iteration(env)

print("Policy Probability Distribution:")
print(policy)
print("")

print("Reshaped Grid Policy (0=up, 1=right, 2=down, 3=left):")
print(np.reshape(np.argmax(policy, axis=1), env.shape))
print("")

print("Value Function:")
print(v)
print("")

print("Reshaped Grid Value Function:")
print(v.reshape(env.shape))
print("")

delta:  1.0
delta:  1.0
delta:  1.0
delta:  0.0
ending training.....
total num of updates through all updates: 4
Policy Probability Distribution:
[[0. 0. 0. 0.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [2. 2. 2. 2.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [2. 2. 2. 2.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]]

Reshaped Grid Policy (0=up, 1=right, 2=down, 3=left):
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Value Function:
[ 0. -1. -2. -3. -1. -2. -3. -2. -2. -3. -2. -1. -3. -2. -1.  0.]

Reshaped Grid Value Function:
[[ 0. -1. -2. -3.]
 [-1. -2. -3. -2.]
 [-2. -3. -2. -1.]
 [-3. -2. -1.  0.]]



In [47]:
# Test the value function
expected_v = np.array([ 0, -1, -2, -3, -1, -2, -3, -2, -2, -3, -2, -1, -3, -2, -1,  0])
np.testing.assert_array_almost_equal(v, expected_v, decimal=2)